# Generated by Django 5.1.4 on 2025-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, choices=[('cs', 'CS'), ('it', 'IT'), ('bba', 'BBA'), ('bed', 'BED'), ('english', 'English')], max_length=20)),
                ('batch', models.CharField(blank=True, choices=[('2k19', '2k19'), ('2k20', '2k20'), ('2k21', '2k21'), ('2k22', '2k22'), ('2k23', '2k23'), ('2k24', '2k24'), ('2k25', '2k25')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=20)),
            ],
        ),
    ]
