# Generated by Django 5.1.4 on 2025-06-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Administration'), ('staff', 'Non-Teaching Staff')], max_length=30)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='department',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='Default question text', max_length=500),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(default='Default value', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('rating', 'Rating')], max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='audiences',
            field=models.ManyToManyField(related_name='forms', to='feedback.audiencetarget'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback.optionset'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='feedback.optionset'),
        ),
    ]
